#ifndef _MAIN_H_
#define _MAIN_H_

#ifndef DEFAULT_PORT_TO_LISTEN
#define DEFAULT_PORT_TO_LISTEN 9443
#endif//DEFAULT_PORT_TO_LISTEN

#ifndef DEFAULT_MAX_PENDING_CONNECTIONS
#define DEFAULT_MAX_PENDING_CONNECTIONS 5
#endif//DEFAULT_MAX_PENDING_CONNECTIONS

#endif // _MAIN_H_
