#ifndef _MAIN_H_
#define _MAIN_H_

#ifndef DEFAULT_PORT_TO_LISTEN
#define DEFAULT_PORT_TO_LISTEN 9443
#endif//DEFAULT_PORT_TO_LISTEN

#ifndef DEFAULT_MAX_PENDING_CONNECTIONS
#define DEFAULT_MAX_PENDING_CONNECTIONS 5
#endif//DEFAULT_MAX_PENDING_CONNECTIONS

#ifndef SCENARIO_ENCHANTED_FOREST
#define SCENARIO_ENCHANTED_FOREST "bosque_encantado"
#endif//SCENARIO_ENCHANTED_FOREST

#ifndef SCENARIO_UNENCHANTED_FOREST
#define SCENARIO_UNENCHANTED_FOREST "bosque_no_encantado"
#endif//SCENARIO_UNENCHANTED_FOREST

#ifndef SCENARIO_FOREST
#define SCENARIO_FOREST "bosque"
#endif//SCENARIO_FOREST

#endif // _MAIN_H_
